# Application
spring.application.name=RevShop
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rev_shop_new_28
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.jpa.properties.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Static Resources
spring.web.resources.static-locations=classpath:/static/
